### ISSUE TITLE
2015 MTD/YTD Section Won't Output in Flex Query

### ISSUE THREAD

**Issue by canada4663** [wesm/ib-flex-analyzer#2]
Great tool!  Wanted to see if you are getting the same issue I am when pulling the annual report for 2015 - basically the MTDYTDPerformanceSummary section isn't populating, so that portion of the script won't work.

I have From / TO date set with the first day of 2015 and December 31, 2015... is it working for you?

**Comment by wesm** [comment]
It's possible they haven't finished beancounting yet. I'll let you know when I have a chance to pull my report

**Comment by Elektra58** [comment]
From pulling many flexqueries I come to the conclusion that the MTDYTDPerformanceSummary section is only included for the last business day per month and the last business day available. I believe this is a constraint from IB's side, not an issue in ib-flex-analyzer.

**Comment by canada4663** [comment]
Yes, when you try to pull historical reports, this is exactly correct.  

That said, you can always pull the most recent MTMYTDPerformanceSummary from the flex query service if you set up the query for YTD or MTD in the reporting setup via web management interface.
